### PR TITLE
gofmt -s -w

### PR DESCRIPTION
**Pull request by peterbourgon**
And other things to improve the Go Report Card.

### CODE REVIEW

**Comment by peterbourgon** [comment]
@ChrisHines [From go vet](https://goreportcard.com/report/github.com/go-kit/kit#go_vet):

```
github.com/go-kit/kit/log/log_test.go
 Line 74: unrecognized printf verb 'n'
 Line 85: unrecognized printf verb 'n'
```

What is meant there, do you think?

**Comment by ae6rt** [comment]
There is no such verb as "%n"?  https://golang.org/pkg/fmt/

**Comment by ChrisHines** [comment]
This is why go vet is sometimes wrong. Type [`gopkg.in/stack.v1.Call`](https://godoc.org/gopkg.in/stack.v1#Call.Format) implements the [`fmt.Formatter`](https://golang.org/pkg/fmt/#Formatter) interface. It mostly responds to standard formatting verbs that go vet is happy with, but it introduces the %n verb for *function name* because none of the traditional verbs made sense and it already had uses for %s and %v.

I have considered filing an issue against go vet along the lines of "don't flag formatting verbs if the corresponding argument implements `fmt.Formatter`", but I have never done so because there are so few implementations of `fmt.Formatter` in the wild that it hardly seems worth the effort.

**Comment by peterbourgon** [comment]
Understood. I guess it is an unfortunate impedance mismatch. Thank you for the patient explanation.

**Comment by ae6rt** [comment]
I see it now.  Sorry for the noise.

**Pull request merged**
