### PR TITLE
An example REST-y service, with gorilla/mux

### PR DESCRIPTION
**Pull request by peterbourgon**
Let me know what you think!

### CODE REVIEW

**Comment by ae6rt** [comment]
Peter, this is beautiful.  This suggested pattern of weaving a well-known http router into go-kit will bring an entirely new group of developers to the go-kit.  (github star predictions for six months from now?) Love it.

**Comment by ae6rt** [comment]
Once I start working with this, one of my first tasks is to see how OAuth2-secured endpoints works with this pattern.  And to explore whether business endpoints can remain unaware that a middleware has allowed them to run because the middleware knows consumption of the specific endpoint is allowed by the provided OAuth2 token scope(s).

**Comment by peterbourgon** [comment]
Yup. My guess — some business middleware will look for the presence of auth keys in the context.Context, and error out if it doesn't find them. Then it'd be the responsibility of a transport middleware (e.g. http.BeforeFunc, or something more custom) to extract information from the transport and populate the context.

**Comment by ae6rt** [comment]
btw, I could not tell:  were you kidding when you said you were going to work on code generation? :)

**Comment by peterbourgon** [comment]
Yes, it's definitely the next thing I have to dive into. No ETA :)

**Pull request merged**
