### PR TITLE
fix sd/etcdv3 bug

### PR DESCRIPTION
**Pull request by wencan**

### CODE REVIEW

**Comment by peterbourgon** [comment]
1. Which bug?
2. This is a breaking change. Can you make it.. not a breaking change? 😇

**Comment by peterbourgon** [comment]
@wencan Friendly ping re: above :)

**Comment by wencan** [comment]
If a service is registered with etcd after GetEntries is executed and before WatchPrefix is executed, kit/sd/etcdv3 will not get it. 
Ci looks broken.
I can build it successfully

**Comment by peterbourgon** [comment]
> If a service is registered with etcd after GetEntries is executed and before WatchPrefix is executed, kit/sd/etcdv3 will not get it.

Can you please write a test case which fails on current master and passes on your branch?

> Ci looks broken. I can build it successfully

Rebase on master and it should be fixed.

**Comment by wencan** [comment]
This difficulty
I need to optimize the client class
Do you allow me to do this?

**Comment by peterbourgon** [comment]
Closing due to nonresponsive contributor.

**Pull request closed without merging**
