### PR TITLE
Some code improvements

### PR DESCRIPTION
**Pull request by sosiska**
* Rewrite some if-else chains as a switch statements. Based on Go style guide: https://golang.org/doc/effective_go.html#switch
* Simplify some functions.
* Improvement of len() comparisons style, because builtin len() function can't return value smaller than zero.
* strings.ToLower comparison changed to strings.EqualFold.
* **gofmt** _examples/addsvc/thrift/gen-go/addsvc/add_service-remote/add_service-remote.go_ file (was done automatically by my IDE  ¯\\_(ツ)_/¯ )

### CODE REVIEW

**Comment by peterbourgon** [comment]
> Rewrite some if-else chains as a switch statements. Based on Go style guide: https://golang.org/doc/effective_go.html#switch

This is a style choice, one version isn't better or worse than the other, by default. Unless there is a clear win in legibility, changing these sorts of things is relatively unproductive code churn. I didn't see anything in the diff that would obviously warrant the changes, if you believe otherwise, please give justification.

> Improvement of len() comparisons style, because builtin len() function can't return value smaller than zero

These were done deliberately. Please revert.

With those changes, happy to merge.

**Comment by sosiska** [comment]
> These were done deliberately. Please revert.

Why check the obviously impossible option?

**Comment by peterbourgon** [comment]
len returns an int, ints can be negative, <= is safer.

**Comment by sosiska** [comment]
> len returns an int, ints can be negative, <= is safer.

I do not agree, the source code is full of places where the result of the len() is compared with 0.

**Comment by peterbourgon** [comment]
If I wrote the code, I used `<=`. If other people wrote the code, I probably didn't pick any nits about it.

**Comment by sosiska** [comment]
> If I wrote the code, I used `<=`. If other people wrote the code, I probably didn't pick any nits about it.

https://github.com/go-kit/kit/blame/master/metrics/internal/lv/space.go#L82  ¯\\(ツ)/¯

**Comment by sosiska** [comment]
> These were done deliberately. Please revert.

Rejected in https://github.com/go-kit/kit/commit/40b2404b3da771def8eb6b7af3dc2ec3194856e8

**Pull request merged**
