### PR TITLE
AMQP Transport 

### PR DESCRIPTION
**Pull request by mattfung**
Hello, 

I noticed that here had been interest in *AMQP* transport similiar to NATS (#681) as well as talks of pubsub support (#295) so I thought I might like to share an implementation of a simple AMQP client & server transport.

Comments/Reviews would be appreciated.

### CODE REVIEW

**Comment by peterbourgon** [comment]
Cool, this looks reasonable at a first glance. As a next step, please run `go vet`, `golint`, and `staticcheck` and fix the relevant errors. A couple of problems that stood out to me: underscores in variable names, and superfluous newlines in function declarations.

**Comment by mattfung** [comment]
May bad with the underscores.. bad python habits.
The problems should be fixed now, lemme know if anything can be improved

**Comment by jstoja** [comment]
Hey @peterbourgon @mattfung any chance that this moves forward? This would be a great addition along NATS!

**Comment by jstoja** [comment]
@mattfung I had some issues with running the tests on my end. Rebasing solve all the tests, would you be able to do that?

**Comment by mattfung** [comment]
make a PR to https://github.com/streadway/amqp with channel listener functionality :)

jokes aside, Id be interested on improvements

**Comment by jstoja** [comment]
Haha yes indeed!
Let’s think about that in another issue ;)

It think this is definitely mergeable! Great job!

**Comment by jstoja** [comment]
@peterbourgon Do you have any feedback on this for merging it? I've used it for a professional project as a demonstration (so with small usage), and it ran several days without any issues.

**Comment by peterbourgon** [comment]
That’s great feedback, thanks. I just need to block off an hour to review.
I’ll do that in the next 2 days. Sorry for the delay; I have a lot on my
plate these days :/

**Comment by jstoja** [comment]
No worries :) just trying to know if help was needed on that!

**Comment by mattfung** [comment]
Sounds good, I'll get them fixed within a day's time.
thx again for putting in the time to do this

**Comment by mattfung** [comment]
Committed the changes. I'm guessing the failed tests occurred because I didn't rebase the code with the latest `master` branch?

Anyhow, let me know if anything needs to be changed.

**Comment by peterbourgon** [comment]
Yes, this seems fine; can you rebase on master?

**Comment by peterbourgon** [comment]
Dang nice

**Comment by TLogik** [comment]
@mattfung I am new to gokit and struggling a bit getting AMQP up and working.
Besides the test do you have a sample app or something that shows how to use the AMQP setup.
I am starting prototyping moving some of out NET services to GO and we rely heavily on RabbitMQ.
Any help is very much appreciated.

**Comment by mattfung** [comment]
@TLogik  for now, heres an implementation of stringsvc4 pub & sub
https://github.com/cloudpbx/kit/tree/amqp/examples/stringsvc4/amqp

Hope this helps.

**Comment by jstoja** [comment]
Awesome! Would be great to have it in this repository too, no?

**Comment by mattfung** [comment]
Thats the plan, my only reservation currently is that the commit makes some breaking changes with the current `stringsvc4` implementation. When I resolve that, I'll create a new merge request.

**Comment by TLogik** [comment]
> Hope this helps.

It helped a lot. Much appreciated.

**Comment by TLogik** [comment]
Hi again @mattfung 
I am using your example as a template, trying to get the behaviour i need.
Questions arise as i work with the implementation.
I find that in the Subscriber.go, func ServeDelivery, the channel for consuming is also used for publishing.
That is somewhat ok, except for at common requirement for subscribing from one Vhost and publishing to another Vhost.
AFAIK you need to create a new connection to each Vhost, create individual channels etc.

i do not seem to be able to setup the internal publisher, in the subscriber.go, for an alternate channel - can you confirm that is not possible in the current implementation?

**Comment by mattfung** [comment]
@TLogik correct, current implementation does not allow for a subscriber to subscribe to one channel (& consequently, Vhost) and publish to another. I am curious on how other frameworks handle this problem if you happen to know of any.

Currently, publishers and subscribers are (for simplicity's sake) tied to one channel. That can change if it is a significant limitation. 

An alternative approach would be to have a subscriber for vhost A trigger a publisher for vhost B.

**Comment by TLogik** [comment]
@mattfung currently we use individual instances of subscriber and publisher with individual connstrings.
I was looking into using go-kit as the toolbox of choice to create a standard to metrics, health, service registration etc, but it is a little hard to extend the transport layer.
i am currently working on a service that needs to batch process messages consumed from MQ and then inserted into SOLR. It is a lot faster to insert in SOLR via batching than individual requests.
This will require a custom amqp implementation to support this.

**Comment by freemanoid** [comment]
@mattfung thanks for the amqp implementation, I've adopted it and it works perfectly! I [see][1] that consuming function automatically publishes some "response". It's not needed for me and I don't see any possibility to turn it off. Can you explain why did you added it? Maybe I'm using amqp wrong.

[1]: https://github.com/go-kit/kit/commit/12210fb6ace19e0496167bb3e667dcd91fa9f69b#diff-8767a31b727acc5ec358b2e23985c87fR114

**Comment by peterbourgon** [comment]
If you're not publishing responses, you're not doing RPC.

**Comment by freemanoid** [comment]
> If you're not publishing responses, you're not doing RPC.

Do you mean this implementation is not about AMQP, but RPC over AMQP?

**Comment by mattfung** [comment]
@freemanoid  Good point, one way AMQP communication is not uncommon. Currently the closest thing to a "no-op" is to use the [NopEncoder](https://github.com/go-kit/kit/blob/8a8a1bb8700078c22421bc35bdcfb140b57c1b3a/transport/amqp/subscriber.go#L163-L170) such that an empty response is sent back.

There are two solutions to implement true "no-op" subscribers, one is to make the "encoder" both encode and send, and use `EncodeNopResponse` (though Im not sure if thats a [good idea](https://github.com/go-kit/kit/pull/746#discussion_r230945887) )

The other option is to add an options/ change the parameter to `NewSubscriber`

**Comment by peterbourgon** [comment]
@freemanoid 

> Do you mean this implementation is not about AMQP, but RPC over AMQP?

Yes. Go kit is concerned exclusively with RPC.

> **Non-goals**
> - Supporting messaging patterns other than RPC (for now) — e.g. MPI, pub/sub, CQRS, etc.

---

@mattfung

> The other option is to add an options/ change the parameter to `NewSubscriber`

For the record, if this is easy, I'd happily take a PR.

**Comment by madshov** [comment]
@mattfung Do you plan any work around adding an option/change parameter to NewSubscriber to no-op subscribers?

**Comment by mattfung** [comment]
@madshov sorry for the slow response, PR is posted #850

**Pull request merged**
