### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by threeaccents**

### CODE REVIEW

**Comment by peterbourgon** [comment]
Thanks!

**Comment by threeaccents** [comment]
Hey man I know it has nothing to do with this but I don't think its worthy of a new issue. What do you think about adding support for queues?

**Comment by peterbourgon** [comment]
Please take the discussion to Slack or the mailing list. Please provide more detail about what you want to do than "adding support for queues" :)

**Comment by peterbourgon** [comment]
Whoops! I thought this was merged.

**Pull request merged**
