### PR TITLE
Add log/term/NewTerminalLogger as log15.TerminalFormat

### PR DESCRIPTION
**Pull request by tgulacsi**
Configurable thorugh LogOpts, bat that's maybe overkill, I don't know.

Try to add the remaining from #111

### CODE REVIEW

**Comment by ChrisHines** [comment]
@tgulacsi Is there any way the level functionality here could build on or work with the log/levels package?

**Comment by tgulacsi** [comment]
One option is to let levels/Levels.TermLogOpts to provide a populated term.LogOpts (ofc that has to move to some common pkg), but as TermLogOpts is almost the same as Levels (with the exception of ctx), maybe factor out the levelKey, ...Value part?
Or create a ColoredLevels copy of Levels?

**Comment by peterbourgon** [comment]
Is this closeable?

**Comment by peterbourgon** [comment]
Whoops, meant that as a question.

**Comment by ChrisHines** [comment]
We can't merge it until it is made more orthogonal with the log/levels package.

@tgulacsi Do you plan to put more work into this?

**Comment by tgulacsi** [comment]
As levels' internals are sealed (Options sets unexported params, no way to retrieve those values), and I don't want to import FgBgColor into levels (to provide a Color function in levels), I don't see a solution to integrate this into log/levels. 
But this is awkward now, to have to duplicate the level key and value info.

**Pull request closed without merging**
