### PR TITLE
Add a log adapter for zerolog.Logger

### PR DESCRIPTION
**Pull request by ozon2**
I am currently using zerolog, and some projects I use are using kitlog, so I made this adapter to make kitlog compatible with zerolog.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@ozon2 The log package has been extracted to a separate module: https://github.com/go-kit/log

The adapter packages has been dropped. There is no need for them to be in the core. I'd suggest releasing it under your name. We can add a link to the readme pointing to your repository.

**Comment by ozon2** [comment]
@sagikazarmark Thanks for the suggestion. Probably won't do it though, I find it a little overkill to release a single file. Anyway if someone searches for an adapter they might stumble upon this PR.

**Comment by peterbourgon** [comment]
Feel free to comment with a link to a gist with the adapter code! IMO this is the perfect kind of thing to copy/paste.

**Comment by ozon2** [comment]
@peterbourgon Good idea!
https://gist.github.com/ozon2/b2150944976da8a9f2cf1a2a1e8c2047

**Pull request closed without merging**
