### PR TITLE
Change default file key string to caller

### LINKED ISSUE #432: log: default StdlibAdapter file key should be "caller"
Not "file". To match the naming of DefaultCaller/UTC.

Open to a PR?

### PR DESCRIPTION
**Pull request by willfaught**
Fixes #432.

### CODE REVIEW

**Comment by willfaught** [comment]
@peterbourgon Looks like TestGauge and TestCounter fail intermittently? Is there a way I can rerun the build?

**Comment by peterbourgon** [comment]
It's not you, it's Circonus. They write their lib so it's basically impossible to test, and change its behavior so the hacks I use stop working. I'll fix it. Sorry for the noise.

**Comment by willfaught** [comment]
Rebased

**Comment by peterbourgon** [comment]
Nice! Thanks!

**Pull request merged**
