### PR TITLE
Make more sence to go.

### PR DESCRIPTION
**Pull request by wangtuanjie**

### CODE REVIEW

**Comment by peterbourgon** [comment]
Failures are related to a gRPC update, I think.

**Comment by wangtuanjie** [comment]
I think we can use `vendor` to manage dependency.

**Comment by peterbourgon** [comment]
> [Go kit] recommend our users use vendoring for all of their dependencies, including Go kit. To avoid compatibility and availability issues, Go kit doesn't vendor its own dependencies, and doesn't recommend use of third-party import proxies.

—https://github.com/go-kit/kit#dependency-management

**Comment by wangtuanjie** [comment]
If Go kit doesn't vendor its own dependencies, it  must keep up upstream changes which is a `big work`.

**Comment by peterbourgon** [comment]
That's correct.

**Comment by peterbourgon** [comment]
Thank you!

**Pull request merged**
