### PR TITLE
Go1.17beta lazy modules test

### PR DESCRIPTION
**Pull request by ChrisHines**
This is just a test, **NOT INTENDED FOR MERGING YET!**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
[Go 1.17 is released](https://twitter.com/golang/status/1427378613289164810)

**Comment by ChrisHines** [comment]
> [Go 1.17 is released](https://twitter.com/golang/status/1427378613289164810)

Indeed. I'll update this PR accordingly soon.

**Comment by ChrisHines** [comment]
I will polish this up and move it out of draft mode within a day now that we have https://github.com/go-kit/log/releases/tag/v0.2.0.

**Comment by ChrisHines** [comment]
Closing this in favor of #1183.

**Pull request closed without merging**
