### PR TITLE
Refactor cmp

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by alexander-melentyev** [comment]
Data race again...
@sagikazarmark, @peterbourgon, please check

**Comment by sagikazarmark** [comment]
Eureka tests sometimes fail...really, we should just get rid of it already.

**Comment by peterbourgon** [comment]
@alexander-melentyev What problem does this solve?

**Comment by peterbourgon** [comment]
I think we should probably just deprecate or remove sd/eureka altogether, it's not really used any more, as far as I know.

**Comment by alexander-melentyev** [comment]
Nothing. 
Code Is shorter

**Comment by alexander-melentyev** [comment]
@peterbourgon I close this?

**Comment by peterbourgon** [comment]
Yeah probably best.

**Pull request closed without merging**
