### PR TITLE
use a TODO context

### LINKED ISSUE #856: kit/metrics/cloudwatch2: fails to build
```
# github.com/go-kit/kit/metrics/cloudwatch2
src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:169:22: not enough arguments in call to req.Send
	have ()
	want (context.Context)
```

Break found by [gopkgs.io](https://gopkgs.io):
https://gopkgs.io/builds/20190406-041800-2e1199d6

### PR DESCRIPTION
**Pull request by h8liu**

### CODE REVIEW

**Comment by peterbourgon** [comment]
```
=== RUN   TestSend
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f0865]

goroutine 11 [running]:
net/http.(*Request).WithContext(...)
	/usr/local/go/src/net/http/request.go:353
github.com/aws/aws-sdk-go-v2/aws.setRequestContext(...)
	/home/build/go/src/github.com/aws/aws-sdk-go-v2/aws/request_context.go:11
```

Doesn't work.

**Comment by h8liu** [comment]
please take a look.

**Comment by h8liu** [comment]
not sure why circleci failed this time.

**Comment by peterbourgon** [comment]
Thank you!

**Pull request merged**
