### PR TITLE
tracing: Fix opentracing ext tagging

### PR DESCRIPTION
**Pull request by bg451**
Fixes the breaking changes introduced into the OpenTracing ext package
by https://github.com/opentracing/opentracing-go/pull/90

### CODE REVIEW

**Comment by peterbourgon** [comment]
Guess this needs to wait until that PR is merged.

**Comment by bg451** [comment]
Do you guys vendor/cache dependencies on your testing CI? That PR was merged almost a week ago so I'm not sure why the tests aren't passing. I'm on master `opentracing-go`, which go-kit master doesn't build with currently.

**Comment by peterbourgon** [comment]
You're right re: the merge. Travis generally doesn't cache; Circle often does. I've kicked off new builds.

**Comment by bg451** [comment]
Ah I figured it out, my local copy of `opentracing-go` ended up in a weird state, closing this. Sorry for the noise!

**Comment by peterbourgon** [comment]
All good in this hood 🉑

**Pull request closed without merging**
