### PR TITLE
Allow multiple HTTP-Headers in Server

### PR DESCRIPTION
**Pull request by klaus**
This is the awaited pull request for the Multi-HTTP Header issue https://github.com/go-kit/kit/issues/643

### CODE REVIEW

**Comment by peterbourgon** [comment]
Looks great! Minor nit, but could we add a test for this behavior? I don't want to regress 😇

**Comment by klaus** [comment]
@peterbourgon sorry, X-mas freeze. will attend to it next couple of days

**Comment by klaus** [comment]
@peterbourgon sorry for the long delay, I hope these tests will suffice, they do fail if you run it against the non-patched code

**Comment by peterbourgon** [comment]
Thanks! 💯

**Pull request merged**
