### PR TITLE
add log.Logger wrapper

### PR DESCRIPTION
**Pull request by shkov**
new log.Logger wrapper for https://github.com/go-kit/kit/issues/867

### CODE REVIEW

**Comment by peterbourgon** [comment]
Is this not an easier approach?

```go
type FlushingLogger struct {
	next log.Logger
	flusher Flusher
}

func (fl FlushingLogger) Log(keyvals ...interface{}) error {
	fl.next.Log(keyvals...)
	fl.flusher.Flush(keyvals...)
	return nil
}
```

**Comment by shkov** [comment]
Do I understand correctly that if i don’t increase the length of keyvals, then there will be no problems with context stack depth consistency?

**Comment by shkov** [comment]
I just feared it https://github.com/go-kit/kit/blob/master/log/log.go#L88

**Comment by ChrisHines** [comment]
I don't want to see `log.context` grow more functionality.

You don't need to worry about the stack depth problem if all the wrapping layers are built up before `log.With` is used on them.

As for the functionality in this PR, the `Flush` method introduced here has the exact same signature as the `Log` method of the `log.Logger` interface. It's not clear to me how this adds any value. An implementation of `log.Logger` can do everything that an implementation of a `log.Flusher` can. A `log.Logger` implementation that adds some buffering or writes to a DB, or whatever works just fine without introducing any new abstractions.

**Comment by shkov** [comment]
It turns out that I can implement my own `log.Logger`, which can write to elasticSearch. I'm not sure now that core of Go kit needed more functionality. Maybe you would like to see the implementation of sending logs to elastic inside of go-kit or something else?

**Comment by peterbourgon** [comment]
My comment in #867 stands:

> Although I'm happy to review a design doc and/or PR [for Elasticsearch support], I'm really dubious that this kind of functionality belongs in core Go kit. My intuition is that it's much better as a third-party adapter.

More concretely, I don't really want to have to maintain Elasticsearch integration tests for the lifetime of Go kit.

**Pull request closed without merging**
