### PR TITLE
Update fargo library

### PR DESCRIPTION
**Pull request by sagikazarmark**
See #1127

I think it's still worth updating, even if we decide to deprecate it.

### CODE REVIEW

**Comment by peterbourgon** [comment]
I understood we'd be doing updates just prior to releases?

**Comment by sagikazarmark** [comment]
Yep, I mostly wanted to use this PR as a reference for the discussion about deprecating/dropping the eureka. The change is trivial, no breaking changes in the library, so I'd say it's worth upgrading along with a deprecation notice.

I don't mind closing this PR and updating dependencies before the next release.

**Comment by peterbourgon** [comment]
OK, as long as it's a one-off :) Just want to reiterate that we shouldn't be processing an unending stream of "update so-and-so dependency" PRs.

**Review by peterbourgon — APPROVED** [review]

**Comment by sagikazarmark** [comment]
Let's repurpose this PR then into deprecating eureka (joined with a dependency update). But that would require having a conversation/making a decision about what and how to deprecate.

Since generics are expected to be available in 1.18 and #843 proposes a large refactor once generics are available, maybe we can start planning that. But as @ChrisHines pointed out earlier: making large changes in smaller chunks is better, so if the introduction of generics is targeted for 1.18, maybe the next Go kit version should be released somewhere after Go 1.17, deprecating the packages that we intend to remove/relocate as part of the larger refactor. That would give people enough time to start migrating away (given these packages actively used).

**Pull request merged**
