### PR TITLE
Fix drift from aws sdk

### LINKED ISSUE #856: kit/metrics/cloudwatch2: fails to build
```
# github.com/go-kit/kit/metrics/cloudwatch2
src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:169:22: not enough arguments in call to req.Send
	have ()
	want (context.Context)
```

Break found by [gopkgs.io](https://gopkgs.io):
https://gopkgs.io/builds/20190406-041800-2e1199d6

### PR DESCRIPTION
**Pull request by nelz9999**
Fixes #856

### CODE REVIEW

**Comment by peterbourgon** [comment]
Unfortunately not..

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f0895]

goroutine 11 [running]:
net/http.(*Request).WithContext(...)
	/usr/local/go/src/net/http/request.go:353
github.com/aws/aws-sdk-go-v2/aws.setRequestContext(...)
	/home/build/go/src/github.com/aws/aws-sdk-go-v2/aws/request_context.go:11
github.com/aws/aws-sdk-go-v2/aws.(*Request).SetContext(...)
	/home/build/go/src/github.com/aws/aws-sdk-go-v2/aws/request.go:226
github.com/aws/aws-sdk-go-v2/service/cloudwatch.PutMetricDataRequest.Send(0xc0000bca00, 0xc00000e800, 0x0, 0x93e320, 0xc00001c080, 0x5cb003c6, 0xc000030760, 0x4a8a27)
	/home/build/go/src/github.com/aws/aws-sdk-go-v2/service/cloudwatch/api.go:1146 +0xc5
github.com/go-kit/kit/metrics/cloudwatch2.(*CloudWatch).Send.func2(0x0, 0x0)
	/home/build/go/src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:169 +0x2de
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000133b0, 0xc0000133e0)
	/home/build/go/src/golang.org/x/sync/errgroup/errgroup.go:57 +0x65
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/build/go/src/golang.org/x/sync/errgroup/errgroup.go:54 +0x74
FAIL	github.com/go-kit/kit/metrics/cloudwatch2	0.018s
```

**Comment by peterbourgon** [comment]
@nelz9999 Seems like this might be solved over in #857, do you want to review that?

**Comment by peterbourgon** [comment]
Obviated by #857.

**Comment by nelz9999** [comment]
Ahh, cool. Sorry I missed that.

**Pull request closed without merging**
