### PR TITLE
[WIP] ratelimit: allow resolving token bucket using request scoped info

### PR DESCRIPTION
**Pull request by glerchundi**
Not tested yet, just a concrete example for #509. I'll extend this in case it seems interesting enough. Thanks for your time @peterbourgon

### CODE REVIEW

**Comment by glerchundi** [comment]
Perhaps token/leaky bucket can be interfaced so that it would be easy to inject your own and customized behaviour, it will decouple from implementation, like:

```
type Bucket interface {
    Take(count int64) time.Duration
    TakeAvailable(count int64) int64
}
```

@peterbourgon I agree that as it's implemented right now it only covers racy use cases but if you abstract the bucket in this way, it would be possible to inject any kind of rate limit implementation, not just the juju's one.

WDYT? Maybe create two different PRs in case you think its worth it?

**Comment by peterbourgon** [comment]
No, there is no need to provide a token bucket abstraction in Go kit. The Middleware abstraction is at the right level: users who want to use something other than the Juju token bucket can/should write the [9 lines of code](https://github.com/go-kit/kit/blob/master/ratelimit/token_bucket.go#L20-L29) required to implement their own Middleware.

**Comment by glerchundi** [comment]
Ok, that being said I will close this PR. Rate limiting is not just Token bucket, there are plenty of implementations using different kind of tools. This is not about the amount of code, I know that it's easy enough to reimplement in client's code but I thought this lib is something, among other things, about best practices. I don't think this lib will be hurt if it abstracts to `ratelimit/middleware.go` `ratelimit/juju/token.go` which would open to any kind of implementation. It seems like there is an inconsistency between how do you decide to use one and **unique** implementation for a pattern like rate limiting and there is another completely different for the service discovery for example!

Sorry if I have bothered you and thanks for your patience.

**Comment by peterbourgon** [comment]
I'd be happy to take a PR to add rate-limiting middlewares that use other, popular rate limiting packages. But I'm definitely not interested in providing abstractions for that, it's too low-level a concern for Go kit to take a stake in it.

**Pull request closed without merging**
