### PR TITLE
wide log tooling

### PR DESCRIPTION
**Pull request by nelz9999**
Was just trying to think how I'd do the one-wide-log-per-request thing, and thought others might benefit from it as well.

Also considered doing it as a `NewJSONArrayLogger`, but figured doing it at the writer level would reduce the amount of time that would need to be locked in mutex.

### CODE REVIEW

**Comment by ChrisHines** [comment]
I am not familiar with this idea. Do you have any references that I can read about the "one-wide-log-per-request thing"?

**Comment by nelz9999** [comment]
Sure. The most I'm hearing about this is from the Honeycomb folks. (Disclaimer: I'm a friend of several of them.)

Charity goes into it in this thread: https://twitter.com/mipsytipsy/status/1042817542648082432
And they have this up too: https://www.honeycomb.io/blog/how-are-structured-logs-different-from-events/

But I got to thinkin', might this have been a useful pattern in a different context with different tools? (Like, e.g. at a previous job where we used Splunk.) I think it might've been useful. At least enough to try to think how I'd do it with the go-kit logger. Which is how we got to this PR. :grin:

**Comment by peterbourgon** [comment]
Related work: https://github.com/peterbourgon/ctxlog

**Comment by peterbourgon** [comment]
A more-general version of that package, in one code block:

```go
type ctxdata struct {
	data map[string]string
}

func (d *ctxdata) set(key, val string) {
	d.data[key] = val
}

func (d *ctxdata) get(key, def string) string {
	if val, ok := d.data[key]; ok {
		return val
	}
	return def
}

func newContextData(ctx context.Context) (context.Context, *ctxdata) {
	d := &ctxdata{data: map[string]string{}}
	return context.WithValue(ctx, ctxdatakey, d), d
}

func contextDataFrom(ctx context.Context) *ctxdata {
	v := ctx.Value(ctxdatakey)
	if v == nil {
		return nil
	}
	d, ok := v.(*ctxdata)
	if !ok {
		return nil
	}
	return d
}

type ctxdatakeytype struct{}

var ctxdatakey ctxdatakeytype
```

And usage:

```go
func middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx, d := newContextData(r.Context())
		defer func() {
			// e.g. log.Print(d.get("key"))
		}()
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func myHandler(w http.ResponseWriter, r *http.Request) {
	contextDataFrom(r.Context()).set("key", "value")
	// ...
}
```

**Comment by peterbourgon** [comment]
Oh, I just saw this was a PR, not an issue. Something _like_ this may make sense to be part of package log—or, probably, a sub-package—but I think it's not quite this. I don't like the coupling to JSON, and it feels too low-level, somehow.

**Comment by nelz9999** [comment]
Hrm. Based on Peter's feedback, I just went looking to see if I could make this more widely usable, outside of JSON. 

I considered converting `jsonArrayWriter` to something like `accumulatingWriter`, and then have the `MarshalJSON` func JIT convert the lines to `RawJSON`.

But then I started looking into the `logfmt` library. It seems that library explicitly eschews any collections as values: https://github.com/go-logfmt/logfmt/blob/master/encode.go#L223 Which I take to mean that this approach is not useful in a `logfmt` scenario.

So I can close out this PR, since there doesn't seem to be an appetite for it.

**Pull request closed without merging**
