### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by peterbourgon** [comment]
Thanks for the tiny li'l contribution! :)

**Comment by shawnps** [comment]
@peterbourgon thank you, this PR was part of a live demo I gave of [Go Report Card](https://goreportcard.com/report/github.com/go-kit/kit) during a conference talk :)

**Comment by peterbourgon** [comment]
Ha! Okay! Now that I have your attention :) how do I get Go Report Card to ignore the generated code from the Thrift compiler? It's bringing my score way down! :)

**Comment by shawnps** [comment]
@peterbourgon ooh, someone recently filed an issue about that https://github.com/gojp/goreportcard/issues/116 I'll have to investigate. Could you point me at one of said files?

Btw, thanks for using the Go Report Card badge on your README!

**Comment by peterbourgon** [comment]
My pleasure! I'll put some links in that issue.

**Pull request merged**
