### PR TITLE
updated thrift to latest Go library adding support for context

### PR DESCRIPTION
**Pull request by basvanbeek**
In our addsvc example we supply a thrift transport which due to the api change in the Thrift Go library was broken. 

This PR adds the support for context.Context as found in the latest Thrift Go library.

### CODE REVIEW

**Comment by basvanbeek** [comment]
travis has an unrelated build failure:
```
The command "go test -race -v ./..." exited with 0.
0.01s$ ./coveralls.bash
/home/travis/gopath/bin/gover
/home/travis/gopath/bin/goveralls
COVERALLS_TOKEN not set
The command "./coveralls.bash" exited with 1.
```

**Comment by peterbourgon** [comment]
What, that's garbage, the env var is clearly set in Travis..... argh

**Comment by peterbourgon** [comment]
> We do not provide [repository environment variables] to untrusted builds, triggered by pull requests from another repository.

https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

😠

**Comment by peterbourgon** [comment]
@basvanbeek Sorry, can you rebase on master?

**Comment by peterbourgon** [comment]
Leeroy Jenkins

**Pull request merged**
