### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by peterbourgon**
More regressions in dependencies, more fixing to do...

### CODE REVIEW

**Comment by peterbourgon** [comment]
@basvanbeek Looks like breaking changes in zipkintracer/zipkinot:

```
# github.com/go-kit/kit/examples/addsvc/cmd/addcli
cmd/addcli/addcli.go:61:22: undefined: zipkintracer.NewHTTPCollector
cmd/addcli/addcli.go:72:16: undefined: zipkintracer.NewRecorder
cmd/addcli/addcli.go:73:20: undefined: zipkintracer.NewTracer
# github.com/go-kit/kit/examples/addsvc/cmd/addsvc [github.com/go-kit/kit/examples/addsvc/cmd/addsvc.test]
cmd/addsvc/addsvc.go:74:22: undefined: zipkintracer.NewHTTPCollector
cmd/addsvc/addsvc.go:85:16: undefined: zipkintracer.NewRecorder
cmd/addsvc/addsvc.go:86:18: undefined: zipkintracer.NewTracer
FAIL    github.com/go-kit/kit/examples/addsvc/cmd/addsvc [build failed]
```

Would this be a quick fix for you?

**Comment by peterbourgon** [comment]
Based on my primitive manual testing, that appears to be the only thing that's broken.

**Comment by basvanbeek** [comment]
Yes... I will fix...

**Comment by basvanbeek** [comment]
@peterbourgon PTAL

**Comment by peterbourgon** [comment]
Thank you.

**Pull request merged**
