### PR TITLE
fix a example bug

### PR DESCRIPTION
**Pull request by shanshanpt**
Fix a example bug.  Then we can route the request like "curl -X POST --data "{\"A\":1, \"B\":2}" 127.0.0.1:8000/addsvc/sum".

### CODE REVIEW

**Comment by peterbourgon** [comment]
No, sorry — the addsvc itself should not prefix its own paths with `addsvc/`. What bug were you fixing, exactly?

**Comment by shanshanpt** [comment]
In old example code, when I execute "curl -X POST --data "{"A":1, "B":2}" 127.0.0.1:8000/addsvc/sum", the response is "404 not found".  Then it's OK after I updated the code. I don't know if I execute the wrong curl-command. Am I misunderstand the example?  Thanks.  :)

**Comment by peterbourgon** [comment]
What happens if you make only the change in examples/apigateway/main.go, and throw away the other change?

**Comment by shanshanpt** [comment]
Also "404". I try it just now.

**Comment by peterbourgon** [comment]
Whoops! There was a bug. Here is the fix:

```diff
diff --git a/examples/apigateway/main.go b/examples/apigateway/main.go
index 01367ec..b357e74 100644
--- a/examples/apigateway/main.go
+++ b/examples/apigateway/main.go
@@ -104,7 +104,7 @@ func main() {
                // HTTP handler, and just install it under a particular path prefix in
                // our router.

-               r.PathPrefix("addsvc/").Handler(addsvc.MakeHTTPHandler(ctx, endpoints, tracer, logger))
+               r.PathPrefix("/addsvc").Handler(http.StripPrefix("/addsvc", addsvc.MakeHTTPHandler(ctx, endpoints, tracer, logger)))
        }

        // stringsvc routes.
```

I've made the fix in master. Can you pull and try again?

**Comment by peterbourgon** [comment]
I'm pretty sure this works, so I'll close the PR. Let me know if it's still broken for you :)

**Pull request closed without merging**
