### PR TITLE
(#796) User should be responsible for request encoding with client endpoint

### PR DESCRIPTION
**Pull request by LasTshaMAN**
TODO:
- check out whether some docs require updating as well (so that they will describe new API usage  instead of the deprecated one)
- increase test coverage (especially check the part about `Content-Length`)

### CODE REVIEW

**Comment by peterbourgon** [comment]
Thanks, I'll work on the build failures.

**Comment by peterbourgon** [comment]
Can you rebase on master?

**Comment by LasTshaMAN** [comment]
Sure I can rebase, will do soon!

**Comment by LasTshaMAN** [comment]
Rebased.

**Comment by LasTshaMAN** [comment]
@peterbourgon, have you had a chance to take a look yet ?

**Comment by peterbourgon** [comment]
Sorry for the delay. We can't break the transport/http API by removing the Client type. Can you not incorporate the changes into that type?

**Comment by peterbourgon** [comment]
More concretely, I would want to see EncodeClientRequestFunc (probably better named CreateRequestFunc) as a field in the Client type, with a default implementation that has the current behavior (http.NewRequest) and an Option to set it to something else.

**Comment by LasTshaMAN** [comment]
> We can't break the transport/http API by removing the Client type

I think this PR does not break it, only deprecates it (at least this is how I intended it to be).

> Can you not incorporate the changes into that type? More concretely, I would want to see EncodeClientRequestFunc (probably better named CreateRequestFunc) as a field in the Client type, with a default implementation that has the current behavior (http.NewRequest) and an Option to set it to something else.

We can go this route, but I see the following major obstacle - we initialize `Client` like this:
```go
func NewClient(
	method string,
	tgt *url.URL,
	enc EncodeRequestFunc,
	dec DecodeResponseFunc,
	options ...ClientOption,
) *Client {
...
```
that is, we **require** the API consumer to pass in `enc EncodeRequestFunc`. 

So, as API consumer if I want to create my requests through `CreateRequestFunc` option (like you are suggesting above) rather than through `EncodeRequestFunc` - what value for `enc` should I pass in `NewClient` ?

**Comment by LasTshaMAN** [comment]
Hey, guys, can we follow-up on this ?

**Comment by ppacher** [comment]
Hi, is there any progress here? I'd be cool to get this merged.

**Comment by peterbourgon** [comment]
I'm sorry for my lack of action on this PR, I simply haven't had the mental bandwidth to devote to this actually somewhat substantial change. I will make time before the end of the week to get it into shape and merged. 

@LasTshaMAN — in the interest of expediency, would it be OK with you if I made a PR to your PR to simply implement whatever changes I felt were appropriate?

**Pull request closed without merging**
